### ISSUE TITLE
weather data

### ISSUE THREAD

**Issue by chi86** [DIRKMJK/bikeride#1]
Hi,
everything works great! I just wanted to ask if you know where I can download weather data?

I recorded a training in June and it would be great, if I could get the weather data from that day.

Thanks!
Best
Chris

**Comment by DIRKMJK** [comment]
Thanks for your feedback! I’m afraid I’ve only used Dutch weather data so far, which is available from the KNMI. Which country are you looking for data from? I may not be able to offer a quick fix but I’d like to look into it.

**Comment by chi86** [comment]
Thanks for the quick reply.
I would be interested in data regarding Austria.
Garmin gives me, what I expect to be the averaged wind velocity and direction and for now I just use this value.

Do you by any change have a data set including good weather-data? I tried to find data, e. g. for the tour de france yet I was not successful.

Thanks!

**Comment by DIRKMJK** [comment]
I’ve added a function to download historical weather data for a specified location, see the updated readme. Hope this helps!

**Comment by chi86** [comment]
Amazing thank you! Works perfectly!!!!
